[package]
name = "uwu-mew-mew-6"
version = "6.2.2"
edition = "2021"

[dependencies]
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
async-openai = { version = "0.19.0", git = "https://github.com/YuraSuper2048/mew-mew-async-openai" }
tiktoken-rs = { version = "0.5.8", features = ["async-openai"] }
futures = "0.3.26"
serde_json = "1.0.114"
serde = { version = "1.0.197", features = ["derive"] }
lazy_static = "1.4.0"
derive_builder = "0.20.0"
uuid = { version = "1.7.0", features = ["v4"] }
regex = "1.10.3"
rand = "0.8.5"
backtrace = "0.3"
log = "0.4.21"
env_logger = "0.11.3"
mime = "0.3"
hex = "0.4.3"

# keep your code optimized ğŸ˜Šâ¤ï¸
[profile.release]
opt-level = 3
strip = true
incremental = true
lto = true